-- MySQL Script generated by MySQL Workbench
-- Wed Mar 14 21:41:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Market
-- -----------------------------------------------------
-- Database for AP Project

-- -----------------------------------------------------
-- Schema Market
--
-- Database for AP Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Market` DEFAULT CHARACTER SET utf8 ;
USE `Market` ;

-- -----------------------------------------------------
-- Table `Market`.`farmer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`farmer` (
  `farmerID` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `earnings` FLOAT NULL,
  `sellerLevel` VARCHAR(45) NULL,
  PRIMARY KEY (`farmerID`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`customer` (
  `clientID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NULL,
  `fullName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `balance` FLOAT NULL,
  PRIMARY KEY (`clientID`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`crops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`crops` (
  `cropID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `farmerID` INT NULL,
  `quantiy` INT NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`cropID`),
  INDEX `farmerID_idx` (`farmerID` ASC),
  CONSTRAINT `farmerID`
    FOREIGN KEY (`farmerID`)
    REFERENCES `Market`.`farmer` (`farmerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`purchases` (
  `purClientID` INT NULL,
  `purFarmerID` INT NULL,
  `Quantity` INT NULL,
  `Price` FLOAT NULL,
  `Date` DATE NULL,
  `purCropID` INT NULL,
  `Location` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`cart` (
  `cartClientID` INT NULL,
  `cartCropID` INT NULL,
  `Quantity` INT NOT NULL,
  `Price` FLOAT NOT NULL,
  `Total` FLOAT NULL,
  INDEX `cropID_idx` (`cartCropID` ASC),
  CONSTRAINT `cartClientID`
    FOREIGN KEY (`cartClientID`)
    REFERENCES `Market`.`customer` (`clientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartCropID`
    FOREIGN KEY (`cartCropID`)
    REFERENCES `Market`.`crops` (`cropID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Market`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Market`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
